name: CI

on:
  push:
    branches: [ "**" ]
  pull_request:
    branches: [ "**" ]

concurrency:
  group: ci-${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Make gradlew executable
        run: chmod +x gradlew

      - name: Validate Gradle Wrapper
        uses: gradle/wrapper-validation-action@v2

      - name: Set up Java 21
        uses: actions/setup-java@v5
        with:
          distribution: temurin
          java-version: 21

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v3
        with:
          cache-read-only: false

      - name: Build (assemble + checks)
        run: ./gradlew --no-daemon build

      - name: Create shaded jar
        run: ./gradlew --no-daemon shadowJar

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: ChefAI-jar
          path: build/libs/ChefAI.jar
          if-no-files-found: warn
